name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: swift build -v
    - name: Show content
      run: ls -la
    - name: Show path
      run: pwd
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tflReceiptCostCounter
        path: __DerivedData/tflReceiptCostCounter/Build/Products/Debug/tflReceiptCostCounter
