name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tflReceiptCostCounter
          path: __DerivedData/tflReceiptCostCounter/Build/Products/Debug/tflReceiptCostCounter
