name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: swift build -c release -v
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tflReceiptCostCounter
        path: .build/release/tflReceiptCostCounter
    - name: Action Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        file: .build/release/tflReceiptCostCounter
